# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  other-plugin:
    version: v2
    config:
      my-other-config: "test"
  test-plugin:
    version: v2
    image: ghcr.io/loft-sh/test-plugin:v1
    imagePullPolicy: Never
    config:
      string: "string"
      int: 123
      map:
        entry: "entry"
      array:
        - entry
    rbac:
      role:
        extraRules:
          - apiGroups: ["example.loft.sh"]
            resources: ["cars"]
            verbs:
              ["create", "delete", "patch", "update", "get", "list", "watch"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["create", "update", "get", "list", "watch"]
