name: ci

on:
  push:
    branches:
      - "**"
  pull_request:



jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Hadolint
        run: |
          curl -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -O hadolint && \
          mv hadolint /usr/local/bin

      - name: Run Hadolint
        working-directory: examples/import-secrets/
        run: |
          hadolint < Dockerfile

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:        
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha            
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: examples/import-secrets/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}