name: Release

on:
  release:
    types: [created]

jobs:
  publish-image:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-22.04

    permissions:
      id-token: write # This is the key for OIDC cosign!
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v2.0.2"
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "::set-output name=release_version::$RELEASE_VERSION"
      - name: Get Docker tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/loft-sh/rancher-nodeless-plugin
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the hooks
        uses: docker/build-push-action@v6
        id: docker_build_hooks
        with:
          file: ./examples/hooks/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/loft-sh/vcluster-example-hooks:${{steps.get_version.outputs.release_version}}"
          labels: ${{ steps.docker_meta.outputs.labels }}
          context: ./examples/hooks
      - name: Images digests for
        run: echo ${{ steps.docker_build_hooks.outputs.digest }}
      - name: Build and push the bootstrap
        uses: docker/build-push-action@v6
        id: docker_build_bootstrap
        with:
          file: ./examples/bootstrap-with-deployment/Dockerfile
          context: ./examples/bootstrap-with-deployment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/loft-sh/vcluster-example-bootstrap-bootstrap-with-deployment:${{steps.get_version.outputs.release_version}}"
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Images digests for bootstrap
        run: echo ${{ steps.docker_build_bootstrap.outputs.digest }}
      - name: Build and push crd sync
        uses: docker/build-push-action@v6
        id: docker_build_crd_sync
        with:
          file: ./examples/crd-sync/Dockerfile
          context: ./examples/crd-sync/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/loft-sh/vcluster-example-crd-sync:${{steps.get_version.outputs.release_version}}"
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Images digests for crd sync
        run: echo ${{ steps.docker_build_crd_sync.outputs.digest }}
