name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.renovaterc'
      - '.renovaterc.json'

permissions: {}

jobs:
  validate-renovate:
    permissions:
      contents: read
      pull-requests: read
    uses: loft-sh/github-actions/.github/workflows/validate-renovate.yaml@c40c1db6d6d24f1b75f6db794efe3a1bbf7cfb1a # validate-renovate/v1
