name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.renovaterc'
      - '.renovaterc.json'

permissions: {}

jobs:
  validate-renovate:
    permissions:
      contents: read
      pull-requests: read
    uses: loft-sh/github-actions/.github/workflows/validate-renovate.yaml@c6a76f19cc302d63d1631853496bce5bf76a4e0a # validate-renovate/v1
