name: Validate Renovate Config

on:
  pull_request:
    paths:
      - 'renovate.json'
      - 'renovate.json5'
      - '.renovaterc'
      - '.renovaterc.json'

permissions: {}

jobs:
  validate-renovate:
    permissions:
      contents: read
      pull-requests: read
    uses: loft-sh/github-actions/.github/workflows/validate-renovate.yaml@b52efbd927586ea78282073f79d2423e552c9f62 # validate-renovate/v1
